# -*- coding: utf-8 -*-
"""Machine_Learning_A1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPtMu4MsHHcfpmHYLjrEqDHsT9w-v-CD

2a) Python Code:
"""

import numpy as np

x = np.matrix([[1, 3, 2],[1, 2, 2],[1, 1, -1],[1, -1, -3]])

y = np.matrix([[3],[1],[-1],[-3]])

xT = x.getT()

xI = xT * x

xInv = xI.getI()

w = xInv * xT * y

w

"""2b) Linear Regression Module 

"""

import numpy as np

from sklearn import linear_model

regression = linear_model.LinearRegression()

regression.fit(x, y)

regression.intercept_

regression.coef_

"""3)"""

x1 = np.matrix([[4.], [3.]])

x2 = np.matrix([[2.], [2.]])

x3 = np.matrix([[1.], [1.]])

x4 = np.matrix([[-2.], [-1.]])

mean1 = (x1 + x2) / 2

mean2 = (x3 + x4) / 2

S_W = ((x1 - mean1) * (x1 - mean1).getT()) + ((x2 - mean1) * (x2 - mean1).getT()) + ((x3 - mean2) * (x3 - mean2).getT()) + ((x4 - mean2) * (x4 - mean2).getT())

W = (S_W.getI()) * (mean1 - mean2)

W

"""4)"""

import pandas as pd

import sklearn.discriminant_analysis as sda

import sklearn.linear_model as lm

df = pd.read_csv('/heart_disease_data.txt', sep= ",", header=0)

data = df.to_numpy()

A = data[:,0:13]

B = data[:,-1]

percep = lm.Perceptron(max_iter=1000)

percep.fit(A,B)

percep.coef_

percep.intercept_

LDA = sda.LinearDiscriminantAnalysis()

LDA.fit(A,B)

LDA.coef_

LDA.intercept_